#thymeleaf模板
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.40.88:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false


  #配置redis连接信息

# redis 主从哨兵配置
#  redis:
#    sentinel:
#      master: mymaster
#      nodes: 42.192.236.2:26380,42.192.236.2:26382,42.192.236.2:26384
    #password: hh974932539hh
  redis:
    host: 192.168.40.88
    port: 6379
    #password: 123456





#日志打印
logging:
  level:
    root: warn
    com.yrp: info
  file: log/-blogpro.log
server:
  port: 80





