#数据库驱动mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.224.29.183/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: hh920124hh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false

  #配置redis连接信息
  redis:
    host: 139.224.29.183
    #password: 123456
    port: 6380

#日志打印
logging:
  level:
    root: info
    com.yrp: debug
  file: log/blog-dev.log
server:
  port: 8080