#数据库驱动mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.224.29.183/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: hh920124hh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false

  #配置redis连接信息
  redis:
    host: 192.168.40.88
    port: 6379
    #password: 123456
    # 数据库索引（默认为0）
    database: 15
    # 连接池配置
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

  # 缓存开启
  cache.enable: true

wx:
  open:
    app_id: wxed9954c01bb89b47  # 微信开放平台 appid
    app_secret: a7482517235173ddb4083788de60b90e  # 微信开放平台 appsecret
    redirect_url: http://guli.shop/api/ucenter/wx/callback  # 微信开放平台 重定向url

#日志打印
logging:
  level:
    root: info
    com.yellowhao: debug
  file: log/blog-dev.log
server:
  port: 8080
